version: "3"

services:
  app:
    container_name: next
    build: .
    ports:
      - 3001:3000
    volumes:
      - .:/home/node/app
    networks:
      - gateway-net

networks:
  gateway-net:
    external: true
