version: "3"

services:
  app:
    container_name: next
    build: .
    # entrypoint: ./.docker/entrypoint.sh
    ports:
      - 3001:3000
    volumes:
      - .:/home/node/app
    networks:
      - gateway-net
    # extra_hosts:
    #   - "host.docker.internal:172.17.0.1"

networks:
  gateway-net:
    external: true
